services:
  hub:
    image: selenium/hub:4.18.1
    container_name: bai4-grid-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"

  chrome-1:
    image: selenium/node-chrome:4.18.1
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 3
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"

  chrome-2:
    image: selenium/node-chrome:4.18.1
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 3
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"

  firefox:
    image: selenium/node-firefox:4.18.1
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 3
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"